Tiger-Tix.Web/Models/EventModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tiger_Tix.Web.Models
{
    public class EventModel
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Time { get; set; }
        public int RemainingTickets { get; set; }

        public override string ToString()
        {
            return $"{Name} at {Time} with {RemainingTickets} tickets left";
        }
    }
}

Tiger-Tix.Web/Models/LoginInfoViewModel.cs
namespace Tiger_Tix.Web.Models
{
    public class LoginInfoViewModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

Tiger-Tix.Web/Models/UserViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;

namespace Tiger_Tix.Web.Models
{
    public enum Role
    {
        InvalidLogin,
        InvalidPassword,
        Student,
        Guest,
        Administrator
    }
    public class UserViewModel
    {
        public UserViewModel(LoginInfoViewModel u)
        {
            Email = u.Email;
            Passhash = BCrypt.Net.BCrypt.HashPassword(u.Password);
            UserRole = Role.InvalidLogin;
        }
        
        public UserViewModel(){}

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Passhash { get; set; }
        public Role UserRole { get; set; }
        // public List<EventModel> AvailableEvents { get; set; }
        // public List<EventModel> BoughtEvents { get; set; }
    }
}

Tiger-Tix.Web/ViewModels/IndexViewModel.cs
namespace Tiger_Tix.Web.ViewModels
{
    public class IndexViewModel
    {
        public string UserName { get; set; }
    }
}

Tiger-Tix.Web/Controllers/AppController.cs
using Microsoft.AspNetCore.Mvc;
using Tiger_Tix.Web.Models;
using Tiger_Tix.Web.Services;

namespace Tiger_Tix.Web
{
    public class AppController : Controller
    {
        private ILoginService LoginService;
        private IEventRepository Events;
        public AppController(ILoginService loginService, IEventRepository events)
        {
            LoginService = loginService;
            Events = events;
        }
       
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.error = false;
            ViewBag.noaccount = false;
            return View();
        }

        [HttpPost]
        public IActionResult Index(LoginInfoViewModel model)
        {
            if (model.Password == null || model.Password == "")
                model.Password = "obviously_wrong_password_value";
            
            UserViewModel UserInfo = LoginService.LoginWithCredentials(model);
            if (UserInfo.UserRole != Role.InvalidLogin && UserInfo.UserRole != Role.InvalidPassword)
            {
                if(UserInfo.UserRole == Role.Administrator)
                    return View("AdministratorView");
                ViewBag.AvailableEvents = Events.Events();
                return View("SplashPage", UserInfo);
            }
            ViewBag.error = UserInfo.UserRole == Role.InvalidPassword;
            ViewBag.noaccount = UserInfo.UserRole == Role.InvalidLogin;
            return View("index");
        }

        public IActionResult CreateAccount()
        {
            return View();
        }
        
        
        [HttpPost]
        public IActionResult CreateAccount(UserViewModel newUser)
        {
            ViewBag.AvailableEvents = Events.Events();
            newUser.UserRole = Role.Guest;
            newUser.Passhash = BCrypt.Net.BCrypt.HashPassword(newUser.Passhash);
            LoginService.AddUser(newUser);
            return View("SplashPage", newUser);
        }

        [HttpPut]
        public IActionResult EditEvent(EventModel newEvent) { 
            Events.AddEvent(newEvent);
            return View("AdministratorView");
        }
        
    }
}

Tiger-Tix.Web/Views/App/AdministratorView.cshtml
@page
@using Tiger_Tix.Web.Views.Shared
@model EventModel

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<p>Here is where an administrator can edit the database</p>
<div>
    @using(@Html.BeginForm("CreateAccount", "App", FormMethod.Post)){
        <p>Welcome Administrator</p>
        <p>Please enter the information for an event</p>
        <div class="row">
             <div class="col-sm">
                 <label for="Name" class="form-label">Event Name</label>
             </div>
             <div class="col-md">
                 @Html.TextBoxFor(m => m.Name, new {@placeholder = "Football Game", @id = "Name", @class="form-control"})
             </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <label for="Time" class="form-label">Event Time</label>
            </div>
            <div class="col-md">
                @Html.TextBoxFor(m => m.Time, new {@id = "Time", @class="form-control", @type="date"})
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <label for="pass" class="form-label">Number of Tickets</label>
            </div>
            <div class="col-md">
                @Html.TextBoxFor(m => m.RemainingTickets, new {@placeholder = "10", @id="pass", @type="number", @class="form-control"})
            </div>
        </div> <br/>
        <input type="submit" class="btn btn-primary" value="Create Event"/>
    }
</div>
</body>
</html>

Tiger-Tix.Web/Views/App/BuyTicket.cshtml
@page
@model Tiger_Tix.Web.Views.App.BuyTicket

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    <p>Here is where a user can pay for a ticket</p> 
</div>
</body>
</html>

Tiger-Tix.Web/Views/App/CreateAccount.cshtml
@page
@model UserViewModel

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    @using(@Html.BeginForm("CreateAccount", "App", FormMethod.Post)){
        <p>Please enter the following information</p>
        <div class="row">
             <div class="col-sm">
                 <label for="Name" class="form-label">Username</label>
             </div>
             <div class="col-md">
                 @Html.TextBoxFor(m => m.Name, new {@placeholder = "name", @id = "Name", @class="form-control"})
             </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <label for="user" class="form-label">Email</label>
            </div>
            <div class="col-md">
                @Html.TextBoxFor(m => m.Email, new {@placeholder = "name@clemson.edu", @id = "user", @class="form-control"})
            </div>
        </div>
        <div class="row">
            <div class="col-sm">
                <label for="pass" class="form-label">Password</label>
            </div>
            <div class="col-md">
                @Html.TextBoxFor(m => m.Passhash, new {@placeholder = "Password", @id="pass", @type="password", @class="form-control"})
            </div>
        </div> <br/>
        <input type="submit" class="btn btn-primary" value="Create Account"/>
    }
</div>
</body>
</html>

Tiger-Tix.Web/Views/App/SplashPage.cshtml
@using Tiger_Tix.Web.Views.Shared
@model UserViewModel

@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <title>Tiger Tix</title>
    <script>
    function myTix()
    {
        alert("Ticket has not been purchased for this event!")
    }
    $("#Events").change(myTix);
    //http://jsfiddle.net/pD56G/1/
    </script>
</head>
<body>
<div>
    <p>
        <h1>Welcome @Model.Name!</h1>
        <br/>
        You are a @Model.UserRole
    </p>
    <br/>
    @{
        List<EventModel> available = (List<EventModel>)ViewBag.AvailableEvents;
    }
    <p>Available Events Are:</p>
    @Html.ListBox( "Events", available.Select( e => new SelectListItem
    {
        Text = e.ToString()
                
    }))
    
    <details>
        <summary>Test Event</summary>
        <p>Test Event will take place on July 24th, 2022 at 12:00 AM. There are currently 
            60 tickets remaining for this event.</p>
    </details>
    
    <br/>
        <label for="events">Choose an event:
            
        </label>
        <select id="Available_Events_are" name="Available_Events_are">
            <option value=""></option>
            @foreach (var e in available)
            {
                <option value="@e.Id">@e.Name</option>
            }
    </select>
    <br><br>
        <input type="submit" value="Purchase Ticket" />
</div>
</body>
<footer>
    <script>
        $("#Events").change(myTix);
    </script>
</footer>
</html>

Tiger-Tix.Web/Views/App/index.cshtml
@page
@model LoginInfoViewModel

@{
    Layout = "_Layout";
    ViewBag.Title = "Tiger Tix Web Interface";
}

<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
</head>
<body>
<div class="d-flex justify-content-center" style="margin-top: 30px;">
    @using (Html.BeginForm("Index", "App", FormMethod.Post))
    {
        <p>Welcome to Tiger Tix!</p>
        <p>The best place for a tiger to buy event tickets</p>
        <p>Please Login:</p>
        <div class="row">
            <div class="col-md">
                <label for="user" class="form-label">Email</label>
            </div>
            <div class="col-lg">
                @Html.TextBoxFor(m => m.Email, new {@placeholder = "name@clemson.edu", @id = "user", @class="form-control"})
            </div>
        </div>
        <div class="row">
            <div class="col-md">
                <label for="pass" class="form-label">Password</label>
            </div>
            <div class="col-lg">
                @Html.TextBoxFor(m => m.Password, new {@placeholder = "Password", @id="pass", @type="password", @class="form-control"})
            </div>
        </div> <br/>
        <div style="@(ViewBag.error ? "display: block" : "display: none")" class="text-danger">The email and password you entered is not correct, please try again <br/></div>
        <div style="@(ViewBag.noaccount ? "display: block" : "display: none")" class="text-danger">
            The email you entered was not associated with any account<br/>
            Would you like to <a href="@Url.Action("CreateAccount")">make an account?</a><br/>
        </div>
                                                                                                                                                                        
        <input type="submit" value="Login" class="btn btn-primary"/>
        <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("CreateAccount")'">Make New Account</button>
    }
</div>
</body>
</html>

Tiger-Tix.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<style>
.center {
    margin:  auto;
}
</style>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"></script>
</head>
<body>@RenderBody()</body>
</html>